import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

 /**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manually creating the sidebar
  tutorialSidebar: [
    {
      type: 'doc',
      label: 'Getting Started',
      id: 'Getting Started/Getting_Started_with_SafeSquid_Secure_Web_Gateway',
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [{type: 'autogenerated', dirName: 'Configure'}],
    },
    {
      type: 'category',
      label: 'How To',
      link: {type: 'doc', id: 'Sidebar/How_To'},
      items: [{ type: 'autogenerated', dirName: 'How To' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{type: 'autogenerated', dirName: 'Troubleshooting'}],
    },
    {
      type: 'category',
      label: 'Application Eco-System',
      link: {type: 'doc', id: 'Sidebar/Application_Eco-System'},
      items: [{type: 'autogenerated', dirName: 'Application Eco-System'}],
    },
    {
      type: 'doc',
      id: 'About SafeSquid SWG/About_SafeSquid_Secure_Web_Gateway',
      label: 'About SafeSquid SWG',
    },
    {
      type: 'doc',
      id: 'FAQs/FAQs',
      label: 'FAQs',
    },
  ],
};

export default sidebars;