name: Build Docs and Publish
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies and build the project
      - run: npm install
      - run: npm run build

      # Install rsync
      - run: apt-get update && apt-get install -y rsync

      # Set up SSH for rsync
      - run: mkdir -p /github/home/.ssh
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > /github/home/.ssh/id_ed25519 && chmod 600 /github/home/.ssh/id_ed25519

      # Deploy for main branch
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: rsync -avz --delete build/ -e "ssh -o StrictHostKeyChecking=no -i /github/home/.ssh/id_ed25519" ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}:${{ vars.REMOTE_PATH }}

      # Deploy for dev branch
      - name: Deploy to staging
        if: github.ref == 'refs/heads/dev'
        run: rsync -avz --delete build/ -e "ssh -o StrictHostKeyChecking=no -i /github/home/.ssh/id_ed25519" ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}:${{ vars.REMOTE_PATH_DEV }}
